####
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"code":"BPQ2K"}' \
  "https://script.google.com/macros/s/AKfycbxmnZptFw_HPOPfqvd4s61_3et9R4LmKZWMB_7aYPoZZmnl77R1yftCibyIidM-xkpHHA/exec"


####
POST https://script.google.com/macros/s/AKfycbzziC3vFI7yJE2PV-2WBknY1a8-iQCMzIg3yQlM2uFEArpLQi1jm5o58H8PeQ4C18iBXw/exec
Content-Type: application/json

{
  "code": "BPQ2K"
}
